language: objective-c
osx_image: xcode7.3
xcode_project: ios/F8v2.xcodeproj
xcode_scheme: F8v2
sudo: false
#before_cache:
#  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - node_modules
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#    - $HOME/travisPOC/node_modules/
env:
  matrix:
    - BUILD_TYPE=jobst-ios
    - BUILD_TYPE=jobst-and
  global:
    - ANDROID_HOME=/usr/local/opt/android-sdk
before_install: ./travis/scripts/before_install.sh
install: ./travis/scripts/install.sh
script: ./travis/scripts/script.sh
before_deploy: ./travis/scripts/before_deploy.sh
deploy:
  - provider: releases
    api_key:
      secure: WqrNw52tQcFwgBai9UOiYIJHIBdMJse+PaInHNgHThgZ7xiF2nLqlX8AwyVdQUm1/WXUoPOk3J374DHF7lbLjBpBdEFvlLwpIlabV3MdNYS+B/Vwxdd16rIER02d3CQAMug93jVXlBAFmfKybR9zjxkoLTwzgwC+mlrh53XPERF9WRKPQW4mejpjS0LhHEYFHjNcN+ara0effJdngsX8ufeB7bol7b0VHISe5poiVfAw6XLYwJ6WpfqtPCoQGQ1dPpPTGAnJXTtk+7dUzj44/1D2SVt4m6BRhB+C91+ZqDHIJ1BxEzmqLMhEkmbospJD31FJav5HOna8EbXhqRf6i/MxUNZNe4jYh6alI1J9ALkQgUrqBxy09NjDe6cjJflEMiUX0PpLoVQa/kJdP/Qe3l6iovMbvX3bkpdDKrHfoOwn+PUBu+HfZAX8pynTwitLkCm2N4EmFcgTLFPNj/40K1/+YEwvgvMREyTDcNsy4UOPV2c4opo/hqM7qASKnWgsZ0FldwXyJ7Zkse4715ENSCjC3ZlD8mWoJstTitwyG6wk4d901wxFTE8bd6b5jTPY6zORBblCZmEwgFOzwprEAeuaYA+z46jbi4xQhjpx1UXg9/LssIYrx1hsHwmaAVKn7WMGMMGdyKBAGGCjcJ787fWDCVeKiLJiBOESB/EWKVA=
    file: "./android/app/build/outputs/apk/$BUILD_TYPE.apk"
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_TYPE = jobst-and
  - provider: releases
    api_key:
      secure: WqrNw52tQcFwgBai9UOiYIJHIBdMJse+PaInHNgHThgZ7xiF2nLqlX8AwyVdQUm1/WXUoPOk3J374DHF7lbLjBpBdEFvlLwpIlabV3MdNYS+B/Vwxdd16rIER02d3CQAMug93jVXlBAFmfKybR9zjxkoLTwzgwC+mlrh53XPERF9WRKPQW4mejpjS0LhHEYFHjNcN+ara0effJdngsX8ufeB7bol7b0VHISe5poiVfAw6XLYwJ6WpfqtPCoQGQ1dPpPTGAnJXTtk+7dUzj44/1D2SVt4m6BRhB+C91+ZqDHIJ1BxEzmqLMhEkmbospJD31FJav5HOna8EbXhqRf6i/MxUNZNe4jYh6alI1J9ALkQgUrqBxy09NjDe6cjJflEMiUX0PpLoVQa/kJdP/Qe3l6iovMbvX3bkpdDKrHfoOwn+PUBu+HfZAX8pynTwitLkCm2N4EmFcgTLFPNj/40K1/+YEwvgvMREyTDcNsy4UOPV2c4opo/hqM7qASKnWgsZ0FldwXyJ7Zkse4715ENSCjC3ZlD8mWoJstTitwyG6wk4d901wxFTE8bd6b5jTPY6zORBblCZmEwgFOzwprEAeuaYA+z46jbi4xQhjpx1UXg9/LssIYrx1hsHwmaAVKn7WMGMMGdyKBAGGCjcJ787fWDCVeKiLJiBOESB/EWKVA=
    file: "$HOME/travisPOC/ios/build/Release-iphoneos/$BUILD_TYPE.ipa"
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_TYPE = jobst-ios
